export const SPINNER_VERBS: string[] = [
  // Thinking
  "Cogitating",
  "Pondering",
  "Contemplating",
  "Ruminating",
  "Deliberating",
  "Speculating",
  "Musing",
  "Reflecting",
  "Meditating",
  "Brooding",
  // Processing
  "Synthesizing",
  "Analyzing",
  "Evaluating",
  "Processing",
  "Computing",
  "Calculating",
  "Interpolating",
  "Correlating",
  "Extrapolating",
  "Simulating",
  // Building
  "Assembling",
  "Compiling",
  "Constructing",
  "Fabricating",
  "Engineering",
  "Architecting",
  "Composing",
  "Drafting",
  "Sculpting",
  "Molding",
  // Searching
  "Parsing",
  "Inspecting",
  "Scanning",
  "Sifting",
  "Excavating",
  "Prospecting",
  "Probing",
  "Surveying",
  "Scouting",
  "Foraging",
  // Transforming
  "Distilling",
  "Extracting",
  "Refining",
  "Transmuting",
  "Alchemizing",
  "Crystallizing",
  "Condensing",
  "Decoding",
  "Encoding",
  "Translating",
  // Crafting
  "Brewing",
  "Forging",
  "Crafting",
  "Weaving",
  "Knitting",
  "Stitching",
  "Baking",
  "Smelting",
  "Tempering",
  "Polishing",
  // Whimsical
  "Percolating",
  "Tinkering",
  "Fiddling",
  "Noodling",
  "Wrangling",
  "Juggling",
  "Conjuring",
  "Summoning",
  "Manifesting",
  "Incubating",
  // Technical
  "Crunching",
  "Hashing",
  "Indexing",
  "Tokenizing",
  "Vectorizing",
  "Normalizing",
  "Serializing",
  "Marshalling",
  "Diffing",
  "Resolving",
]

export const WITTY_PHRASES: string[] = [
  // Classic programmer humor
  "Trying to exit Vim",
  "Reticulating splines",
  "Downloading more RAM",
  "Bribing the linter",
  "Blaming the compiler",
  "Searching for the missing semicolon",
  "Reversing the polarity",
  "Warming up the vacuum tubes",
  "Feeding the hamsters",
  "Defragmenting the matrix",
  // Tech references
  "Applying percussive maintenance",
  "Aligning the cosmic rays",
  "Consulting the magic 8-ball",
  "Locating the any key",
  "Rotating the tires on the cloud",
  "Untangling the spaghetti code",
  "Herding the electric sheep",
  "Calibrating the flux capacitor",
  "Rebooting the mainframe",
  "Compiling the compilations",
  // AI/LLM humor
  "Hallucinating responsibly",
  "Tokenizing the vibes",
  "Attention is all I need right now",
  "Performing gradient descent on your problem",
  "Reducing the perplexity",
  "Running inference at the speed of thought",
  "Embedding your request in latent space",
  "Softmaxing the possibilities",
  "Backpropagating through time",
  "Overfitting to your preferences",
  // Dev culture
  "Deploying to production on a Friday",
  "Clearing the npm cache, just in case",
  "It works on my machine™",
  "Reading the error message this time",
  "Checking Stack Overflow",
  "Merging the merge conflicts",
  "Rebasing on top of hopes and dreams",
  "Reviewing my own PR",
  "Writing documentation (just kidding)",
  "Incrementing the version number",
  // Existential
  "Contemplating the halting problem",
  "Questioning the meaning of null",
  "Solving P vs NP (almost done)",
  "Counting to infinity (halfway there)",
  "Searching for the last bug",
  "Optimizing for developer happiness",
  "Converting caffeine to code",
  "Rearranging deck chairs on the Titanic",
  "Polishing the bike shed",
  "Yak shaving in progress",
  // Playful
  "Spinning up the hamster wheel",
  "Charging the laser beams",
  "Dusting off the algorithms",
  "Sharpening the bits",
  "Warming up the neural pathways",
]

export const INFORMATIVE_TIPS: string[] = [
  // Navigation
  "Search history with Ctrl+R",
  "Up arrow recalls your last prompt",
  "Press Tab to autocomplete files",
  "Navigate messages with j/k keys",
  // Session management
  "Use /clear to reset context",
  "Use /stats to see session usage",
  "Use /save to export the conversation",
  "Use /compact to compress context when running low",
  // Interaction
  "Interrupt generation with Esc",
  "Type /help for all commands",
  "Toggle tools with /tools",
  "Add @/path to include a file in context",
  // Editing
  "Edit a message by selecting it and pressing e",
  "Copy a message with y when selected",
  "Delete a message with d when selected",
  // Configuration
  "Set your preferred model in config with /model",
  "Permission rules can auto-approve trusted tools",
  "Custom agents can be configured per-project",
  // Workflow
  "Use subagents to parallelize complex tasks",
  "Paste images directly into the prompt",
  "The status bar shows live token usage",
  "Context compaction preserves key information",
  // Advanced
  "MCP servers extend available tools",
  "Custom commands can be added via /commands",
  "Session history persists between restarts",
  "Use /diff to review all file changes",
  "Fork a session to explore alternatives",
  "Workspaces scope sessions to project directories",
  "The prompt supports multi-line input with Shift+Enter",
]

export const TURN_COMPLETION_VERBS: string[] = [
  "Baked",
  "Brewed",
  "Crunched",
  "Cooked",
  "Finished",
  "Done",
  "Ready",
  "Served",
]
