/**
 * CLI tool to generate and manage LiteAI API keys (liteai-api-node).
 *
 * Uses RS256 asymmetric signing (jose library):
 *   - SIGNING:      requires the private key (admin only)
 *   - VERIFICATION: uses the public key (shipped with app)
 *
 * Usage:
 *
 *   # Generate RSA key pair
 *   bun scripts/keygen.ts keys
 *
 *   # Create an API key (reads private key from keys/api_private.pem)
 *   bun scripts/keygen.ts create --user alice@example.com
 *
 *   # Create with explicit private key path
 *   bun scripts/keygen.ts create --user alice@example.com --key /path/to/api_private.pem
 *
 *   # Create a key valid for 90 days
 *   bun scripts/keygen.ts create --user bob@example.com --days 90
 *
 *   # Inspect a key (decode without verification)
 *   bun scripts/keygen.ts inspect <token>
 *
 *   # Verify a key against the public key
 *   bun scripts/keygen.ts verify <token>
 *
 * Private key resolution order:
 *   1. --key flag
 *   2. LITEAI_API_PRIVATE_KEY env var (PEM content)
 *   3. ~/.liteai/keys/api_private.pem
 *   4. ./keys/api_private.pem (monorepo dev)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import * as jose from "jose"

const ISSUER = "liteai"
const ALGORITHM = "RS256"

// ── Key resolution ──────────────────────────────────────────────────────────

const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..")

function findPrivateKey(keyArg?: string): string {
  // 1. Explicit file path
  if (keyArg) {
    if (!existsSync(keyArg)) {
      console.error(`ERROR: Private key file not found: ${keyArg}`)
      process.exit(1)
    }
    return readFileSync(keyArg, "utf-8")
  }

  // 2. Env var (PEM content)
  const envVal = process.env.LITEAI_API_PRIVATE_KEY
  if (envVal) return envVal

  // 3. ~/.liteai/keys/
  const homePath = join(homedir(), ".liteai", "keys", "api_private.pem")
  if (existsSync(homePath)) return readFileSync(homePath, "utf-8")

  // 4. ./keys/ (monorepo dev)
  const devPath = join(appRoot, "keys", "api_private.pem")
  if (existsSync(devPath)) return readFileSync(devPath, "utf-8")

  console.error("ERROR: No private key found. Provide one via:")
  console.error("  --key /path/to/api_private.pem")
  console.error("  LITEAI_API_PRIVATE_KEY env var")
  console.error("  ~/.liteai/keys/api_private.pem")
  throw new Error("No private key found")
}

function findPublicKey(): string {
  // Env var
  const envVal = process.env.JWT_PUBLIC_KEY_API
  if (envVal) return envVal

  // keys/api_public.pem
  const keyPath = join(appRoot, "keys", "api_public.pem")
  if (existsSync(keyPath)) return readFileSync(keyPath, "utf-8")

  // src/keys/index.ts embedded key — not easily extracted at runtime
  console.error("ERROR: No public key found for verification.")
  throw new Error("No public key found")
}

// ── Commands ────────────────────────────────────────────────────────────────

async function cmdKeys(bits: number): Promise<void> {
  const { privateKey, publicKey } = await jose.generateKeyPair(ALGORITHM, {
    modulusLength: bits,
  })

  const privatePem = await jose.exportPKCS8(privateKey)
  const publicPem = await jose.exportSPKI(publicKey)

  const keysDir = join(appRoot, "keys")
  mkdirSync(keysDir, { recursive: true })

  writeFileSync(join(keysDir, "api_private.pem"), privatePem, "utf-8")
  writeFileSync(join(keysDir, "api_public.pem"), `${publicPem.trim()}\n`, "utf-8")

  // Embed public key in TypeScript module
  const modulePath = join(appRoot, "src", "keys", "index.ts")
  mkdirSync(dirname(modulePath), { recursive: true })
  writeFileSync(
    modulePath,
    `/**
 * Embedded RSA public keys for JWT verification.
 *
 * This file is auto-generated by scripts/keygen.ts keys.
 * Do NOT edit manually — regenerate keys and re-run the script.
 */

export const API_PUBLIC_KEY = \`${publicPem.trim()}\`;
`,
    "utf-8",
  )

  console.log()
  console.log("=".repeat(60))
  console.log("  LiteAI API — RSA Key Pair Generated")
  console.log("=".repeat(60))
  console.log(`  Key size: ${bits} bits`)
  console.log()
  console.log(`  Private: ${join(keysDir, "api_private.pem")}`)
  console.log(`  Public:  ${join(keysDir, "api_public.pem")}`)
  console.log(`  Module:  ${modulePath}`)
  console.log()
  console.log("  ⚠ Move the private key to a secure location:")
  console.log(`    move ${join(keysDir, "api_private.pem")} %USERPROFILE%\\.liteai\\keys`)
  console.log()
  console.log("  ℹ Public key has been embedded in src/keys/index.ts.")
  console.log("=".repeat(60))
  console.log()
}

async function cmdCreate(user: string, days: number, keyArg?: string): Promise<void> {
  const privatePem = findPrivateKey(keyArg)
  const privateKey = await jose.importPKCS8(privatePem, ALGORITHM)

  const now = Math.floor(Date.now() / 1000)
  const token = await new jose.SignJWT({ sub: user })
    .setProtectedHeader({ alg: ALGORITHM })
    .setIssuedAt(now)
    .setIssuer(ISSUER)
    .setExpirationTime(`${days}d`)
    .sign(privateKey)

  console.log()
  console.log("=".repeat(60))
  console.log("  LiteAI API Key Created")
  console.log("=".repeat(60))
  console.log()
  console.log(`  User:    ${user}`)
  console.log(`  Expires: ${days} days`)
  console.log("  Algo:    RS256 (asymmetric)")
  console.log()
  console.log(`  Key: ${token}`)
  console.log()
  console.log("  ⚠ Save this key now — it will NOT be shown again!")
  console.log("=".repeat(60))
  console.log()
}

function cmdInspect(token: string): void {
  try {
    const claims = jose.decodeJwt(token)

    const expTs = claims.exp
    const iatTs = claims.iat ?? 0
    const expDt = expTs ? new Date(expTs * 1000) : null
    const iatDt = new Date(iatTs * 1000)

    const expStr = expDt ? expDt.toISOString() : "never"
    const iatStr = iatDt.toISOString()

    const now = new Date()
    const isExpired = expDt !== null && now > expDt
    let status = isExpired ? "❌ EXPIRED" : "✅ Valid"

    if (!isExpired && expDt !== null) {
      const remainingDays = Math.floor((expDt.getTime() - now.getTime()) / 86400000)
      status += ` (${remainingDays} days remaining)`
    }

    console.log()
    console.log("  JWT Claims (unverified)")
    console.log(`  ${"-".repeat(40)}`)
    console.log(`  User (sub):   ${claims.sub ?? "N/A"}`)
    console.log(`  Issuer (iss): ${claims.iss ?? "N/A"}`)
    console.log(`  Issued at:    ${iatStr}`)
    console.log(`  Expires at:   ${expStr}`)
    console.log(`  Status:       ${status}`)
    console.log()
  } catch {
    console.error("ERROR: Could not decode token.")
    process.exit(1)
  }
}

async function cmdVerify(token: string): Promise<void> {
  const publicPem = findPublicKey()

  try {
    const publicKey = await jose.importSPKI(publicPem, ALGORITHM)
    const { payload } = await jose.jwtVerify(token, publicKey, {
      issuer: ISSUER,
      requiredClaims: ["sub", "iat", "iss"],
    })

    const expTs = payload.exp
    const expStr = expTs ? new Date(expTs * 1000).toISOString() : "never"

    console.log()
    console.log("  ✅ Key is valid for liteai-api!")
    console.log(`     User:    ${payload.sub}`)
    console.log(`     Expires: ${expStr}`)
    console.log()
  } catch (err) {
    if (err instanceof jose.errors.JWTExpired) {
      console.error("  ❌ Verification failed: Token has expired.")
    } else {
      console.error(`  ❌ Verification failed: ${err instanceof Error ? err.message : String(err)}`)
    }
    process.exit(1)
  }
}

// ── CLI ─────────────────────────────────────────────────────────────────────

function printUsage(): void {
  console.log("Usage: bun scripts/keygen.ts <command> [options]")
  console.log()
  console.log("Commands:")
  console.log("  keys                        Generate RSA key pair")
  console.log("  create --user <email>       Create a new API key")
  console.log("  inspect <token>             Decode and inspect a key")
  console.log("  verify <token>              Verify a key with the public key")
  console.log()
  console.log("Options for 'keys':")
  console.log("  --bits <n>                  RSA key size (default: 2048)")
  console.log()
  console.log("Options for 'create':")
  console.log("  --user, -u <email>          Username or email (required)")
  console.log("  --days, -d <n>              Days until expiration (default: 30)")
  console.log("  --key, -k <path>            Path to RSA private key PEM file")
}

function getArg(args: string[], flags: string[]): string | undefined {
  for (const flag of flags) {
    const idx = args.indexOf(flag)
    if (idx !== -1 && idx + 1 < args.length) {
      return args[idx + 1]
    }
  }
  return undefined
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const command = args[0]

  if (!command || command === "--help" || command === "-h") {
    printUsage()
    process.exit(0)
  }

  switch (command) {
    case "keys": {
      const bits = Number.parseInt(getArg(args, ["--bits"]) || "2048", 10)
      await cmdKeys(bits)
      break
    }
    case "create": {
      const user = getArg(args, ["--user", "-u"])
      if (!user) {
        console.error("ERROR: --user is required for 'create' command.")
        process.exit(1)
      }
      const days = Number.parseInt(getArg(args, ["--days", "-d"]) || "30", 10)
      const key = getArg(args, ["--key", "-k"])
      await cmdCreate(user, days, key)
      break
    }
    case "inspect": {
      const token = args[1]
      if (!token) {
        console.error("ERROR: token argument is required.")
        process.exit(1)
      }
      cmdInspect(token)
      break
    }
    case "verify": {
      const token = args[1]
      if (!token) {
        console.error("ERROR: token argument is required.")
        process.exit(1)
      }
      await cmdVerify(token)
      break
    }
    default:
      console.error(`ERROR: Unknown command '${command}'`)
      printUsage()
      process.exit(1)
  }
}

main().catch((err) => {
  console.error("Fatal error:", err)
  process.exit(1)
})
